name: WordPress Plugin CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  plugin_checks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wc-sovendus

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'
          tools: composer:v2.2
          coverage: none

      - name: Configure Composer
        run: |
          composer config --global allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer config --global allow-plugins.composer/installers true

      - name: Install dependencies
        run: |
          composer install --no-progress --prefer-dist --optimize-autoloader

      - name: PHP Compatibility Check
        run: |
          vendor/bin/phpcs --standard=PHPCompatibility --runtime-set testVersion 7.0- --ignore=vendor/* .
          vendor/bin/phpcs --standard=WordPress --ignore=vendor/* .

      - name: Run PHPStan for Static Analysis
        working-directory: SovendusApp
        run: |
          vendor/bin/phpstan analyse --memory-limit=2G -c phpstan.neon || exit 1
